%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
image_width: 800
image_height: 600
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 280.0830152838839
   fy: 280.0830152838839
   cx: 400.0
   cy: 300.0
